apiVersion: v1

kind: ConfigMap
metadata:
  labels:
    app: start-configmap
  name: start-configmap

data:
  dbconnection.properties:
{{ toYaml .Values.configMap.dbconnection_properties | indent 4 }}
  start.sh: 
{{ toYaml .Values.configMap.start_sh | indent 4 }}
