apiVersion: networking.k8s.io/v1
kind: Ingress
{{- with .Values.ingress }}
metadata:
  {{- with $.Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
#    cert-manager.io/common-name: "{{ .commonName }}.{{ .domain }}"
#    {{- if .clusterIssuer }}
#    cert-manager.io/cluster-issuer: {{ .clusterIssuer }}
#    {{- end }}
#    {{- if .class }}
#    kubernetes.io/ingress.class: {{ .class }}
#    {{- end }}
  name: {{ $.Values.deployment.name }}-ingress
spec:
  rules:
{{- range $.Values.ingress.spec.rules }}
  - host: {{ .host }}
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ $.Values.deployment.name }}-application-svc
            port:
              number: 9443
          
{{- end }}
  tls:
{{- range $.Values.ingress.spec.tls }}
  - hosts:
      {{ .host }}
{{- end }}
    secretName: "{{ $.Values.deployment.name }}"
{{- end }}
