{{- range $ingress := .Values.ingress }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $ingress.name }}
  annotations:
{{ toYaml $ingress.annotations | indent 4 }}
spec:
  rules:
  - host: {{ $ingress.host }}
    http:
      paths:
      {{ if $ingress.hasMultiPath }} 
{{ toYaml $ingress.paths | indent 8 }}      
      {{ else }}  
      - path: /
        backend:
          serviceName: {{ $.Release.Name }}-application-svc
          servicePort: tomcat-https
{{ end }}

  tls:
  - hosts:
    - {{ $ingress.host }}
{{- end }}
