{{- range $ingress := .Values.ingress }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
{{ toYaml $ingress.annotations | indent 4 }}
#    cert-manager.io/common-name: "{{ .commonName }}.{{ .domain }}"
#    {{- if .clusterIssuer }}
#    cert-manager.io/cluster-issuer: {{ .clusterIssuer }}
#    {{- end }}
#    {{- if .class }}
#    kubernetes.io/ingress.class: {{ .class }}
#    {{- end }}
  name: {{ $ingress.name }}-ingress
spec:
  rules:
  - host: {{ $ingress.host }}
    http:
      paths:
      {{ if $ingress.hasMultiPath }} 
{{ toYaml $ingress.paths | indent 8 }}
      {{ else }}
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ $.Values.appName }}-application-svc
            port:
              number: 9443         
{{ end }}
  tls:
  - hosts:
    - {{ $ingress.host }}
    secretName: "{{ $.Values.deployment.name }}"
  {{- end }}

