apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-application-svc
spec:
  selector:
    app: apex-{{ .Release.Name }}-application
  ports:
  - name: apachewg-https
    port: 8443
    protocol: TCP
    targetPort: 8443
  - name: tomcat-https
    port: 9443
    protocol: TCP
    targetPort: 9443
  - name: tomcat-ajp
    port: 9009
    protocol: TCP
    targetPort: 9009
  - name: tomcat-http
    port: 9080
    protocol: TCP
    targetPort: 9080
  type: ClusterIP
status:
  loadBalancer: {}
